name: sample

on:
  workflow_dispatch:
  push:
    tags: [ 'v-*']

permissions:
  id-token: write
  contents: read

jobs:
  sample:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Sample command
        run: aws s3 ls
